# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cebaf3ec55be9c29e480f793c389adc3f9b283d94bd60d0245e3a83ac8d169aaf16f56139dd7a205c54572d478a14d5f3416516cfe674994c61cbd898b5dd278

test:
  secret_key_base: 72d345d95e7caa6ae554a0e8b09d895a860c441c75c6fdce2371ea20dcd8bfe7ed93ca258b2098934ab44c9b1983fd706d62eaf191826e4fd3aeb3f58a75a890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
